name: tests-coverage
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
            - name: chekout repo
              uses: actions/checkout@v2
            - name: setup python
              uses: actions/setup-python@v2
            - name: Install dependencies
              run: |
                  pip install poetry
                  make install
            - name: codeclimate upload
              uses: paambaati/codeclimate-action@v3.0.0
              env:
                CC_TEST_REPORTER_ID: efc8df94636b76cb7fb0afd82d7e7822f8c6fceef839c00877f3ffe2b5222a3b
              with:
                coverageCommand: make test-coverage
                debug: true